remote_theme: jekyll/minima
title: "Kelvin-Martin Muthomi"
description: "Software engineer"
author:
  name: "Kelvin-Martin Muthomi"
  email: "kelvinmartinmuthomi@gmail.com"
social:
  github: "https://github.com/Muthommi"
  linkedin: "www.linkedin.com/in/martin-kelvin-muthomi"
include: ["style.css"]
